### ISSUE TITLE
如果systemed安装的deb包如何通过配置文件修改默认配置

### ISSUE THREAD

**Issue by chenxudong2020** [gngpp/thunder#123]
如果systemed安装的deb包如何通过配置文件修改默认配置，请给出默认配置文件设置的格式 谢谢
大佬的项目牛逼，资源占用低的多

**Comment by gngpp** [comment]
啥配置文件格式

**Comment by chenxudong2020** [comment]
> 啥配置文件格式

-c, --config-path <CONFIG_PATH>

**Comment by gngpp** [comment]
这是存储迅雷配置路径

**Comment by chenxudong2020** [comment]
好吧 我以为程序的路径 这个程序可以配置成https吗 我自己有证书和key的情况下

**Comment by gngpp** [comment]
我之后准备重构，这个http服务不支持https

**Comment by chenxudong2020** [comment]
好吧 最好是原生支持 https 安装时候指定域名  和证书文件夹 
我现在可以暂时通过nginxWebUI这种 进行代理了 内部实现了自动申请证书

**Comment by gngpp** [comment]
现在原生支持TLS了，具体我还没测试过有没有问题，https://github.com/gngpp/thunder/releases/tag/v1.0.0

**Comment by LondyGhost** [comment]
怎么修改路径？我是archlinux
