### ISSUE TITLE
编译安装有问题，无法正常编译，并且deb安装也无法使用

### ISSUE THREAD

**Issue by netll** [gngpp/thunder#138]
系统是debian VPS机，deb安装后访问5055端口，网页显示Something went wrong: Failed to split_once header
删了后
之后尝试编译安装，有以下报错，搞不定了
error: failed to parse manifest at `/root/thunder/Cargo.toml`

Caused by:
  failed to parse the `edition` key

Caused by:
  supported edition values are `2015` or `2018`, but `2021` is unknown

**Comment by yang1010x** [comment]
同样的提示：Something went wrong: Failed to split_once header
